job "jenkins_agent" {

  datacenters = ["dc1"]
  type        = "service"

  constraint {
    attribute = "${attr.kernel.name}"
    value     = "linux"
  }

  group "jenkins_agent" {

    network {
      mode = "host"
      port "ssh" {
        static = 2222
        to = 22
      }
      port "dind" {
        static = 2375
      }
    }

    update {
      max_parallel      = 1
      min_healthy_time  = "15s"
      healthy_deadline  = "15m"
      progress_deadline = "20m"
      auto_revert       = false
    }

    task "jenkins_agent" {

      driver = "docker"
      config {
        image = "alexchub/jenkins-agent-ssh:latest-jdk11"
        auth {
          username = "alexchub"
          password = "618a851c-2b1a-4485-994c-fb48b70407fc"
        }
        ports = ["ssh"]
          volumes = [
          "/bin/docker:/usr/bin/docker"
        ]
      }

      env {
        JENKINS_AGENT_SSH_PUBKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCipApejGxhqX0R+xyJYK/g74fBmthTUyiLQlbgKABTajuhIoABSzL/dGxFlSp61X1v4OUMf5ppmWMbRaOY4EKleuVnpOdzt1d5Bc1EhjWhArMG6DCVJQC43dQrvSE+E0gqmG4UociVUxGrpsaxy/AGMrmeJK2bdO9J00dV6GvwsCr/UHa5DQikNikSPoDwSHHiASFJ3fA+ZwvbYJV8s0mHOWxsR99ezcLd10qxgUZtMcjSthLqhN43cDttR6FqB70Rwe+pGtv6j6PgfvLndSlWyms92K7BZVM/336b2QVkPu+Bk67Dldt/KMNYz2idHpa62SP3nz0r+yYrQ84CUvRy7aAkI7imSDy9bAvUx5B2wlGEIeZucscwdWtM64ykGMwXWllxeGxh8o+FL3pBKqWzP/ita1wALOaC8SL7bDk3lBvQojXerVSU4skass0eCGRYmCdMpo7RHU/EIXmuyaPEbbAVVId83ptEfkReWDEyQt09OGVVUGb1e1JdtbYe+MM="
        DOCKER_HOST="tcp://${NOMAD_HOST_IP_dind}:2375"
      }

      service {
        tags = ["jenkins-agent", "jenkins-agent.service.consul"]
        name = "jenkins-agent"
        port = "ssh"
        check {
          type     = "tcp"
          port     = "ssh"
          interval = "10s"
          timeout  = "5s"
        }
      }

      resources {
        cpu    = 300  # MHz
        memory = 300 # Mb
      }

    } # task end

    task "docker_dind" {

      driver = "docker"
      config {
        image = "docker:dind"
        ports = ["dind"]
        privileged = "true"
      }

      env {
        DOCKER_TLS_CERTDIR=""
      }

      resources {
        cpu    = 200  # MHz
        memory = 200 # Mb
      }

    } # task end
  }   # group end
}     # job end