job "jenkins_agent" {

  datacenters = ["dc1"]
  type        = "service"

  constraint {
    attribute = "${attr.kernel.name}"
    value     = "linux"
  }

  group "jenkins_agent" {

    network {
      mode = "host"
      port "ssh" {
        static = 2222
        to = 22
      }
      port "dind" {
        static = 2375
      }
    }

    update {
      max_parallel      = 1
      min_healthy_time  = "15s"
      healthy_deadline  = "15m"
      progress_deadline = "20m"
      auto_revert       = false
    }

    task "jenkins_agent" {

      driver = "docker"
      config {
        image = "alexchub/jenkins-agent-ssh:latest-jdk11"
        auth {
          username = "alexchub"
          password = "618a851c-2b1a-4485-994c-fb48b70407fc"
        }
        ports = ["ssh"]
          volumes = [
          "/bin/docker:/usr/bin/docker"
        ]
      }

      env {
        JENKINS_AGENT_SSH_PUBKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDn+CafaREUWelx3l5txQ+6dXIA/siQFdx8MO+JN3spgQs+RT1o3H/W/4gdNrncP+Q+tHwRF/Okpefcqeb0RBpEJg6TOuvOCOnIZKPBwsKIvGRg+C11pwu7ViDimF6l6u4kAnYU1UCe/+SyR+5M8lGZzk/ilsg78TJUZ6ge1ELMHzJBjWVkD8mUuK8wSimHkndO6IMj8xNyHKF3eimhZlGPjSIrasS53mbkHm962qe1vfxgJii9EjOYe0Y15InlNnwcfWqzGQuXb6UgAvmESzq28DJRIyQfh+LaGNCgOto1TyB5JYAEWtbkVElPnSvX74rkUfb1MZigFxHmIlYGaeC8nL4M3l5SnyIXc1kRDKwIHHAYwOqDUzewMT4x6FnT/EcZvAi/RFm5FdKLVgvp2VD5u74gnP4hTrRmoeLVVfLCS0gXqqH5FXWuYoo1qp/QEgOZckq2qphVuKZEdnFg8cheQNI5cf9oF/60MT3i8JKpnPcJCH1CFkGZPq6rdDk0c+U="
        DOCKER_HOST="tcp://${NOMAD_HOST_IP_dind}:2375"
      }

      service {
        tags = ["jenkins-agent", "jenkins-agent.service.consul"]
        name = "jenkins-agent"
        port = "ssh"
        check {
          type     = "tcp"
          port     = "ssh"
          interval = "10s"
          timeout  = "5s"
        }
      }

      resources {
        cpu    = 300  # MHz
        memory = 300 # Mb
      }

    } # task end

    task "docker_dind" {

      driver = "docker"
      config {
        image = "docker:dind"
        ports = ["dind"]
        privileged = "true"
      }

      env {
        DOCKER_TLS_CERTDIR=""
      }

      resources {
        cpu    = 200  # MHz
        memory = 200 # Mb
      }

    } # task end
  }   # group end
}     # job end