AWX_ADMIN_USER=$AWX_ADMIN_USER
AWX_ADMIN_PASSWORD=$AWX_ADMIN_PASSWORD

DATABASE_USER=$DATABASE_USER
DATABASE_NAME=$DATABASE_NAME
DATABASE_HOST=$DATABASE_HOST
DATABASE_PORT=$DATABASE_PORT
DATABASE_PASSWORD=$DATABASE_PASSWORD

REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT

MEMCACHED_HOST=$MEMCACHED_HOST
MEMCACHED_PORT=$MEMCACHED_PORT